### PR TITLE
Specify hook type

### PR DESCRIPTION
**Pull request by atugushev**
Fixes running `bandit` check on non-python files. Filter files by hook type. 

See https://pre-commit.com/#pre-commit-configyaml---hooks

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thank you !
I'll release this in the next hours

**Comment by atugushev** [comment]
Thanks!

**Comment by Lucas-C** [comment]
This has been released under v1.0.4

**Comment by atugushev** [comment]
FTR finally `bandit` has been released https://github.com/PyCQA/bandit/releases/tag/1.6.0!

**Pull request merged**
